languages:
  Python: true
engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "./src/"
